//! [`Memory`] struct — the core domain object for the memory service.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::{MemoryType, VisibilityLevel};

/// A single memory record stored in the system.
///
/// Memory records combine natural-language content with structured metadata
/// (type, tags, visibility) so they can be semantically searched and
/// access-controlled per actor.
///
/// # ID Format
///
/// IDs are generated by [`Memory::generate_id`] in the format
/// `mem_<unix_ms>_<8-char-uuid-prefix>`, e.g. `mem_1718000000000_a1b2c3d4`.
///
/// # Access Control
///
/// The three-tier visibility model is enforced by [`Memory::is_visible_to`].
///
/// # Examples
///
/// ```rust
/// use memory::types::{Memory, MemoryType, VisibilityLevel};
/// use chrono::Utc;
///
/// let now = Utc::now();
/// let memory = Memory {
///     id: Memory::generate_id(),
///     content: "The capital of France is Paris.".to_string(),
///     memory_type: MemoryType::Information,
///     tags: vec!["geography".to_string()],
///     created_by: "agent-1".to_string(),
///     owner: None,
///     created_at: now,
///     updated_at: now,
///     visibility: VisibilityLevel::Public,
///     shared_with: vec![],
///     references: vec![],
/// };
///
/// assert!(memory.is_visible_to(None));
/// assert!(memory.is_visible_to(Some("anyone")));
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Memory {
    /// Unique identifier in the format `mem_<unix_ms>_<8-char-uuid-prefix>`.
    pub id: String,

    /// The natural-language content of the memory.
    pub content: String,

    /// Semantic category of this memory record.
    #[serde(rename = "type")]
    pub memory_type: MemoryType,

    /// Free-form tags for filtering and organisation.
    #[serde(default)]
    pub tags: Vec<String>,

    /// The actor (agent or user identifier) that created this memory.
    pub created_by: String,

    /// Optional owner; may differ from `created_by` when memories are
    /// transferred or attributed to a different principal.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,

    /// Timestamp when this memory was first stored.
    pub created_at: DateTime<Utc>,

    /// Timestamp of the most recent mutation.
    pub updated_at: DateTime<Utc>,

    /// Access-control tier for this memory.
    #[serde(default)]
    pub visibility: VisibilityLevel,

    /// Actors allowed to read this memory when visibility is [`VisibilityLevel::Shared`].
    /// Ignored for `Public` and `Private` memories.
    #[serde(default)]
    pub shared_with: Vec<String>,

    /// IDs of other memories that this record references or relates to.
    #[serde(default)]
    pub references: Vec<String>,
}

impl Memory {
    /// Generate a new memory ID in the format `mem_<unix_ms>_<8-char-uuid-prefix>`.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use memory::types::Memory;
    ///
    /// let id = Memory::generate_id();
    /// assert!(id.starts_with("mem_"));
    ///
    /// let parts: Vec<&str> = id.splitn(3, '_').collect();
    /// assert_eq!(parts[0], "mem");
    /// assert!(parts[1].parse::<i64>().is_ok(), "timestamp part must be numeric");
    /// assert_eq!(parts[2].len(), 8, "uuid prefix must be 8 chars");
    /// ```
    pub fn generate_id() -> String {
        let timestamp = Utc::now().timestamp_millis();
        let prefix = Uuid::new_v4().to_string()[..8].to_string();
        format!("mem_{timestamp}_{prefix}")
    }

    /// Return `true` when `actor` is permitted to read this memory.
    ///
    /// | Visibility | Condition                                                   |
    /// |------------|-------------------------------------------------------------|
    /// | `Public`   | Always visible                                              |
    /// | `Private`  | Actor must match `created_by` or `owner`                    |
    /// | `Shared`   | Actor must match `created_by`, `owner`, or be in `shared_with` |
    ///
    /// Passing `None` as `actor` represents an unauthenticated request; only
    /// `Public` memories are visible to anonymous callers.
    ///
    /// # Examples
    ///
    /// ```rust
    /// use memory::types::{Memory, MemoryType, VisibilityLevel};
    /// use chrono::Utc;
    ///
    /// let now = Utc::now();
    /// let mut memory = Memory {
    ///     id: Memory::generate_id(),
    ///     content: "secret".to_string(),
    ///     memory_type: MemoryType::Information,
    ///     tags: vec![],
    ///     created_by: "alice".to_string(),
    ///     owner: None,
    ///     created_at: now,
    ///     updated_at: now,
    ///     visibility: VisibilityLevel::Private,
    ///     shared_with: vec![],
    ///     references: vec![],
    /// };
    ///
    /// assert!(!memory.is_visible_to(None));
    /// assert!(memory.is_visible_to(Some("alice")));
    /// assert!(!memory.is_visible_to(Some("bob")));
    /// ```
    pub fn is_visible_to(&self, actor: Option<&str>) -> bool {
        match self.visibility {
            VisibilityLevel::Public => true,
            VisibilityLevel::Private => match actor {
                Some(a) => self.created_by == a || self.owner.as_deref() == Some(a),
                None => false,
            },
            VisibilityLevel::Shared => match actor {
                Some(a) => {
                    self.created_by == a
                        || self.owner.as_deref() == Some(a)
                        || self.shared_with.contains(&a.to_string())
                }
                None => false,
            },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_memory(visibility: VisibilityLevel) -> Memory {
        let now = Utc::now();
        Memory {
            id: Memory::generate_id(),
            content: "Test content".to_string(),
            memory_type: MemoryType::Information,
            tags: vec!["test".to_string()],
            created_by: "user1".to_string(),
            owner: None,
            created_at: now,
            updated_at: now,
            visibility,
            shared_with: vec![],
            references: vec![],
        }
    }

    // ── ID generation ──────────────────────────────────────────────────────

    #[test]
    fn test_generate_id_prefix() {
        let id = Memory::generate_id();
        assert!(id.starts_with("mem_"), "id should start with 'mem_'");
    }

    #[test]
    fn test_generate_id_three_parts() {
        let id = Memory::generate_id();
        let parts: Vec<&str> = id.splitn(3, '_').collect();
        assert_eq!(parts.len(), 3, "id should have three underscore-separated parts");
    }

    #[test]
    fn test_generate_id_timestamp_is_numeric() {
        let id = Memory::generate_id();
        let parts: Vec<&str> = id.splitn(3, '_').collect();
        assert!(parts[1].parse::<i64>().is_ok(), "middle part must be a numeric timestamp");
    }

    #[test]
    fn test_generate_id_uuid_prefix_length() {
        let id = Memory::generate_id();
        let parts: Vec<&str> = id.splitn(3, '_').collect();
        assert_eq!(parts[2].len(), 8, "uuid prefix must be exactly 8 characters");
    }

    #[test]
    fn test_generate_id_uniqueness() {
        let ids: std::collections::HashSet<String> =
            (0..100).map(|_| Memory::generate_id()).collect();
        assert_eq!(ids.len(), 100, "all generated IDs should be unique");
    }

    // ── Public visibility ──────────────────────────────────────────────────

    #[test]
    fn test_public_visible_to_anonymous() {
        let m = make_memory(VisibilityLevel::Public);
        assert!(m.is_visible_to(None));
    }

    #[test]
    fn test_public_visible_to_any_actor() {
        let m = make_memory(VisibilityLevel::Public);
        assert!(m.is_visible_to(Some("anyone")));
        assert!(m.is_visible_to(Some("stranger")));
    }

    // ── Private visibility ─────────────────────────────────────────────────

    #[test]
    fn test_private_invisible_to_anonymous() {
        let m = make_memory(VisibilityLevel::Private);
        assert!(!m.is_visible_to(None));
    }

    #[test]
    fn test_private_visible_to_creator() {
        let m = make_memory(VisibilityLevel::Private);
        assert!(m.is_visible_to(Some("user1")));
    }

    #[test]
    fn test_private_invisible_to_stranger() {
        let m = make_memory(VisibilityLevel::Private);
        assert!(!m.is_visible_to(Some("stranger")));
    }

    #[test]
    fn test_private_visible_to_owner() {
        let mut m = make_memory(VisibilityLevel::Private);
        m.owner = Some("owner1".to_string());
        assert!(m.is_visible_to(Some("owner1")));
        assert!(m.is_visible_to(Some("user1"))); // creator still has access
        assert!(!m.is_visible_to(Some("other")));
    }

    // ── Shared visibility ──────────────────────────────────────────────────

    #[test]
    fn test_shared_invisible_to_anonymous() {
        let m = make_memory(VisibilityLevel::Shared);
        assert!(!m.is_visible_to(None));
    }

    #[test]
    fn test_shared_visible_to_creator() {
        let m = make_memory(VisibilityLevel::Shared);
        assert!(m.is_visible_to(Some("user1")));
    }

    #[test]
    fn test_shared_visible_to_listed_actors() {
        let mut m = make_memory(VisibilityLevel::Shared);
        m.shared_with = vec!["friend1".to_string(), "friend2".to_string()];
        assert!(m.is_visible_to(Some("friend1")));
        assert!(m.is_visible_to(Some("friend2")));
    }

    #[test]
    fn test_shared_invisible_to_unlisted_actor() {
        let mut m = make_memory(VisibilityLevel::Shared);
        m.shared_with = vec!["friend1".to_string()];
        assert!(!m.is_visible_to(Some("stranger")));
    }

    #[test]
    fn test_shared_visible_to_owner() {
        let mut m = make_memory(VisibilityLevel::Shared);
        m.owner = Some("owner1".to_string());
        assert!(m.is_visible_to(Some("owner1")));
    }

    // ── Serialisation ──────────────────────────────────────────────────────

    #[test]
    fn test_serialization_type_field_renamed() {
        let m = make_memory(VisibilityLevel::Public);
        let json = serde_json::to_string(&m).unwrap();
        assert!(json.contains("\"type\":\"information\""), "memory_type should serialize as 'type'");
    }

    #[test]
    fn test_serialization_visibility_lowercase() {
        let m = make_memory(VisibilityLevel::Public);
        let json = serde_json::to_string(&m).unwrap();
        assert!(json.contains("\"visibility\":\"public\""));
    }

    #[test]
    fn test_serialization_owner_omitted_when_none() {
        let m = make_memory(VisibilityLevel::Public);
        let json = serde_json::to_string(&m).unwrap();
        assert!(!json.contains("\"owner\""), "owner should be omitted when None");
    }

    #[test]
    fn test_roundtrip() {
        let m = make_memory(VisibilityLevel::Shared);
        let json = serde_json::to_string(&m).unwrap();
        let parsed: Memory = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.id, m.id);
        assert_eq!(parsed.content, m.content);
        assert_eq!(parsed.memory_type, m.memory_type);
        assert_eq!(parsed.visibility, m.visibility);
    }

    #[test]
    fn test_references_field_defaults_empty() {
        let now = Utc::now();
        let json = serde_json::json!({
            "id": "mem_1_abc12345",
            "content": "hello",
            "type": "information",
            "created_by": "bot",
            "created_at": now,
            "updated_at": now,
        });
        let m: Memory = serde_json::from_value(json).unwrap();
        assert!(m.references.is_empty());
    }
}
