//! SeaORM entity for the `agents` table.

use sea_orm::entity::prelude::*;

/// SeaORM model for the `agents` table.
///
/// JSON columns (`tool_policy`, `env`) are stored as TEXT and deserialized
/// manually in the storage layer to preserve the existing serde representations.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "agents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub status: String,
    pub working_dir: String,
    pub user: Option<String>,
    pub shell: String,
    /// Stored as INTEGER (0/1); mapped to `bool` in the domain layer.
    pub interactive: i32,
    pub prompt: Option<String>,
    /// Stored as INTEGER (0/1); mapped to `bool` in the domain layer.
    pub worktree: i32,
    pub system_prompt: Option<String>,
    /// Path to a file containing the system prompt. Nullable TEXT.
    pub system_prompt_file: Option<String>,
    /// Whether to append the system prompt instead of replacing. Stored as INTEGER (0/1).
    pub append_system_prompt: i32,
    pub session_id: Option<String>,
    /// JSON-serialized [`crate::types::ToolPolicy`].
    pub tool_policy: String,
    /// Execution backend type (e.g., "tmux", "docker"). Defaults to "tmux".
    pub backend_type: Option<String>,
    pub model: Option<String>,
    /// JSON-serialized `HashMap<String, String>`.
    pub env: String,
    pub created_at: String,
    pub updated_at: String,
    /// Optional token-count threshold that triggers an automatic context clear.
    /// Stored as nullable INTEGER; maps to `Option<u64>` in the domain layer.
    pub auto_clear_threshold: Option<i64>,
    /// Optional network policy for Docker containers (e.g., "internet", "isolated", "host_network").
    /// Stored as nullable TEXT; maps to `Option<NetworkPolicy>` in the domain layer.
    pub network_policy: Option<String>,
    /// Custom Docker image override for this agent. Nullable TEXT.
    pub docker_image: Option<String>,
    /// JSON-serialized `Vec<VolumeMount>` for additional Docker volume mounts.
    pub extra_mounts: Option<String>,
    /// JSON-serialized `ResourceLimits` (cpu_limit, memory_limit_mb).
    pub resource_limits: Option<String>,
    /// JSON-serialized `Vec<String>` of additional directory paths.
    /// Maps to Claude Code's `--add-dir` flag.
    pub additional_dirs: String,
    /// JSON-serialized `Vec<String>` of communicate room names.
    /// The agent is auto-joined to these rooms when it connects to the orchestrator.
    pub rooms: String,
    /// The exact `claude` command string generated by `build_claude_command()` and
    /// sent to the execution backend when the agent was spawned or restarted.
    /// Nullable so that agents created before this column existed have no value.
    pub launch_command: Option<String>,
    /// OS process ID of the agent's subprocess. Used during startup
    /// reconciliation to check if the process survived a service restart.
    pub pid: Option<i64>,
    /// Optional project UUID (stored as TEXT) grouping this agent with related
    /// workflows and rooms.  NULL when the agent is not assigned to a project.
    pub project_id: Option<String>,
    /// Whether this agent is a built-in system agent. Stored as INTEGER (0/1).
    /// System agents are created programmatically and managed by the orchestrator;
    /// user-created agents always have this set to 0.
    pub built_in: i32,
    /// JSON-serialized `HashMap<String, McpServerConfig>` of MCP servers for
    /// the agent's Claude session. NULL when no servers are configured.
    pub mcp_servers: Option<String>,
    /// Optional organization UUID for tenant scoping.  NULL when not
    /// scoped (dev/test mode without gateway).
    pub organization_id: Option<String>,
    /// The kind of agent to run, resolved to an AAP adapter at launch (e.g.
    /// "claude"). NOT NULL with a default of "claude" for pre-existing rows.
    pub agent_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
