//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub id: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub working_dir: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub user: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub shell: String,
    pub interactive: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub prompt: Option<String>,
    pub worktree: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub system_prompt: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub tmux_session: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub tool_policy: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub model: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub env: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub updated_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
