//! Migration: add `launch_command` column to the `agents` table.
//!
//! Adds one column:
//! - `launch_command` (TEXT NULLABLE): the exact `claude` command string that
//!   was generated by `build_claude_command()` and sent to the execution
//!   backend when the agent was spawned or restarted.  Stored as nullable TEXT
//!   so that existing rows (before this migration) have no value.

use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();

        let stmt = "ALTER TABLE agents ADD COLUMN launch_command TEXT";
        if let Err(e) = db.execute_unprepared(stmt).await {
            // Idempotent: ignore if column already exists (e.g., re-run).
            if !e.to_string().contains("duplicate column name") {
                return Err(e);
            }
        }

        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        // SQLite < 3.35.0 does not support DROP COLUMN, so we leave
        // the column in place on rollback for simplicity.
        Ok(())
    }
}
