#\!/usr/bin/env bash
# generate-config.sh — Generate prometheus.yml based on AGENTD_ENV.
#
# Environment variables:
#   AGENTD_ENV                        — "production" or "development" (default: development)
#   AGENTD_ORCHESTRATOR_SERVICE_URL   — Override orchestrator target (e.g. http://host:port)
#   AGENTD_COMMUNICATE_SERVICE_URL    — Override communicate target
#   AGENTD_NOTIFY_SERVICE_URL         — Override notify target
#   AGENTD_ASK_SERVICE_URL            — Override ask target
#   AGENTD_WRAP_SERVICE_URL           — Override wrap target
#   AGENTD_MEMORY_SERVICE_URL         — Override memory target
#   AGENTD_MONITOR_SERVICE_URL        — Override monitor target
#
# Usage:
#   AGENTD_ENV=production ./generate-config.sh
#   AGENTD_ORCHESTRATOR_SERVICE_URL=http://10.0.0.5:7006 ./generate-config.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT="${SCRIPT_DIR}/prometheus.yml"

ENV="${AGENTD_ENV:-development}"

# --- Port defaults per environment -----------------------------------
if [ "$ENV" = "production" ]; then
  ENV_LABEL="prod"
  DEFAULT_ORCHESTRATOR="127.0.0.1:7006"
  DEFAULT_COMMUNICATE="127.0.0.1:7010"
  DEFAULT_NOTIFY="127.0.0.1:7004"
  DEFAULT_ASK="127.0.0.1:7001"
  DEFAULT_WRAP="127.0.0.1:7005"
  DEFAULT_MEMORY="127.0.0.1:7008"
  DEFAULT_MONITOR="127.0.0.1:7003"
else
  ENV_LABEL="dev"
  DEFAULT_ORCHESTRATOR="127.0.0.1:17006"
  DEFAULT_COMMUNICATE="127.0.0.1:17010"
  DEFAULT_NOTIFY="127.0.0.1:17004"
  DEFAULT_ASK="127.0.0.1:17001"
  DEFAULT_WRAP="127.0.0.1:17005"
  DEFAULT_MEMORY="127.0.0.1:17008"
  DEFAULT_MONITOR="127.0.0.1:17003"
fi

# --- Helper: extract host:port from a URL ----------------------------
extract_host_port() {
  local url="$1"
  # Strip scheme (http:// or https://)
  echo "$url" | sed -E 's|^https?://||; s|/.*$||'
}

# --- Apply per-service env var overrides ------------------------------
if [ -n "${AGENTD_ORCHESTRATOR_SERVICE_URL:-}" ]; then
  TARGET_ORCHESTRATOR="$(extract_host_port "$AGENTD_ORCHESTRATOR_SERVICE_URL")"
else
  TARGET_ORCHESTRATOR="$DEFAULT_ORCHESTRATOR"
fi

if [ -n "${AGENTD_COMMUNICATE_SERVICE_URL:-}" ]; then
  TARGET_COMMUNICATE="$(extract_host_port "$AGENTD_COMMUNICATE_SERVICE_URL")"
else
  TARGET_COMMUNICATE="$DEFAULT_COMMUNICATE"
fi

if [ -n "${AGENTD_NOTIFY_SERVICE_URL:-}" ]; then
  TARGET_NOTIFY="$(extract_host_port "$AGENTD_NOTIFY_SERVICE_URL")"
else
  TARGET_NOTIFY="$DEFAULT_NOTIFY"
fi

if [ -n "${AGENTD_ASK_SERVICE_URL:-}" ]; then
  TARGET_ASK="$(extract_host_port "$AGENTD_ASK_SERVICE_URL")"
else
  TARGET_ASK="$DEFAULT_ASK"
fi

if [ -n "${AGENTD_WRAP_SERVICE_URL:-}" ]; then
  TARGET_WRAP="$(extract_host_port "$AGENTD_WRAP_SERVICE_URL")"
else
  TARGET_WRAP="$DEFAULT_WRAP"
fi

if [ -n "${AGENTD_MEMORY_SERVICE_URL:-}" ]; then
  TARGET_MEMORY="$(extract_host_port "$AGENTD_MEMORY_SERVICE_URL")"
else
  TARGET_MEMORY="$DEFAULT_MEMORY"
fi

if [ -n "${AGENTD_MONITOR_SERVICE_URL:-}" ]; then
  TARGET_MONITOR="$(extract_host_port "$AGENTD_MONITOR_SERVICE_URL")"
else
  TARGET_MONITOR="$DEFAULT_MONITOR"
fi

# --- Generate prometheus.yml -----------------------------------------
cat > "$OUTPUT" << EOF
# Prometheus configuration for agentd local observability stack.
#
# Auto-generated by generate-config.sh (AGENTD_ENV=${ENV}).
# Do not edit manually — re-run ./generate-config.sh to regenerate.
#
# Usage:
#   prometheus --config.file=infra/prometheus/prometheus.yml
#
# Or via the launchd plist:
#   launchctl load ~/Library/LaunchAgents/com.agentd.prometheus.plist

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # Attach these labels to every time series and alert when communicating
  # with external systems.
  external_labels:
    env: '${ENV_LABEL}'
    cluster: 'agentd-local'

# Alerting configuration (optional — add rules in a separate file)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['localhost:9093']

# Rule files (optional)
# rule_files:
#   - "alert_rules.yml"

scrape_configs:
  # Orchestrator — agent management, workflow scheduling, dispatch
  - job_name: 'agentd-orchestrator'
    static_configs:
      - targets: ['${TARGET_ORCHESTRATOR}']
        labels:
          service: 'orchestrator'

  # Communicate — WebSocket rooms and real-time messaging
  - job_name: 'agentd-communicate'
    static_configs:
      - targets: ['${TARGET_COMMUNICATE}']
        labels:
          service: 'communicate'

  # Notify — notification ingestion and delivery
  - job_name: 'agentd-notify'
    static_configs:
      - targets: ['${TARGET_NOTIFY}']
        labels:
          service: 'notify'

  # Ask — approval requests and human-in-the-loop gates
  - job_name: 'agentd-ask'
    static_configs:
      - targets: ['${TARGET_ASK}']
        labels:
          service: 'ask'

  # Wrap — PTY session and tmux agent launcher
  - job_name: 'agentd-wrap'
    static_configs:
      - targets: ['${TARGET_WRAP}']
        labels:
          service: 'wrap'

  # Memory — vector-backed knowledge store
  - job_name: 'agentd-memory'
    static_configs:
      - targets: ['${TARGET_MEMORY}']
        labels:
          service: 'memory'

  # Monitor — system monitoring and health checks
  # Uses /prom-metrics to avoid conflict with the JSON /metrics endpoint
  - job_name: 'agentd-monitor'
    metrics_path: '/prom-metrics'
    static_configs:
      - targets: ['${TARGET_MONITOR}']
        labels:
          service: 'monitor'
EOF

echo "Generated ${OUTPUT} (env=${ENV})"
