#!/usr/bin/env bash
# generate-config.sh - Generate a prometheus.yml based on AGENTD_ENV.
#
# Writes to the path given as $1, or stdout if no argument is provided.
# Never modifies the checked-in development configuration.
#
# Environment variables:
#   AGENTD_ENV                        - "production" or "development" (default: development)
#   AGENTD_ORCHESTRATOR_SERVICE_URL   - Override orchestrator target (e.g. http://host:port)
#   AGENTD_COMMUNICATE_SERVICE_URL    - Override communicate target
#   AGENTD_NOTIFY_SERVICE_URL         - Override notify target
#   AGENTD_ASK_SERVICE_URL            - Override ask target
#   AGENTD_WRAP_SERVICE_URL           - Override wrap target
#   AGENTD_MEMORY_SERVICE_URL         - Override memory target
#   AGENTD_MONITOR_SERVICE_URL        - Override monitor target
#
# Usage:
#   ./generate-config.sh                          # write to stdout
#   ./generate-config.sh /tmp/prometheus.yml      # write to file
#   AGENTD_ENV=production ./generate-config.sh    # production ports

set -euo pipefail

OUTPUT="${1:-/dev/stdout}"

ENV="${AGENTD_ENV:-development}"

# --- Port defaults per environment -----------------------------------
if [ "$ENV" = "production" ]; then
  ENV_LABEL="prod"
  DEFAULT_ORCHESTRATOR="127.0.0.1:7006"
  DEFAULT_COMMUNICATE="127.0.0.1:7010"
  DEFAULT_NOTIFY="127.0.0.1:7004"
  DEFAULT_ASK="127.0.0.1:7001"
  DEFAULT_WRAP="127.0.0.1:7005"
  DEFAULT_MEMORY="127.0.0.1:7008"
  DEFAULT_MONITOR="127.0.0.1:7003"
else
  ENV_LABEL="dev"
  DEFAULT_ORCHESTRATOR="127.0.0.1:17006"
  DEFAULT_COMMUNICATE="127.0.0.1:17010"
  DEFAULT_NOTIFY="127.0.0.1:17004"
  DEFAULT_ASK="127.0.0.1:17001"
  DEFAULT_WRAP="127.0.0.1:17005"
  DEFAULT_MEMORY="127.0.0.1:17008"
  DEFAULT_MONITOR="127.0.0.1:17003"
fi

# --- Helper: extract host:port from a URL ----------------------------
extract_host_port() {
  local url="$1"
  # Strip scheme (http:// or https://) and any trailing path
  echo "$url" | sed -E 's|^https?://||; s|/.*$||'
}

# --- Apply per-service env var overrides ------------------------------
TARGET_ORCHESTRATOR="${AGENTD_ORCHESTRATOR_SERVICE_URL:+$(extract_host_port "$AGENTD_ORCHESTRATOR_SERVICE_URL")}"
TARGET_ORCHESTRATOR="${TARGET_ORCHESTRATOR:-$DEFAULT_ORCHESTRATOR}"

TARGET_COMMUNICATE="${AGENTD_COMMUNICATE_SERVICE_URL:+$(extract_host_port "$AGENTD_COMMUNICATE_SERVICE_URL")}"
TARGET_COMMUNICATE="${TARGET_COMMUNICATE:-$DEFAULT_COMMUNICATE}"

TARGET_NOTIFY="${AGENTD_NOTIFY_SERVICE_URL:+$(extract_host_port "$AGENTD_NOTIFY_SERVICE_URL")}"
TARGET_NOTIFY="${TARGET_NOTIFY:-$DEFAULT_NOTIFY}"

TARGET_ASK="${AGENTD_ASK_SERVICE_URL:+$(extract_host_port "$AGENTD_ASK_SERVICE_URL")}"
TARGET_ASK="${TARGET_ASK:-$DEFAULT_ASK}"

TARGET_WRAP="${AGENTD_WRAP_SERVICE_URL:+$(extract_host_port "$AGENTD_WRAP_SERVICE_URL")}"
TARGET_WRAP="${TARGET_WRAP:-$DEFAULT_WRAP}"

TARGET_MEMORY="${AGENTD_MEMORY_SERVICE_URL:+$(extract_host_port "$AGENTD_MEMORY_SERVICE_URL")}"
TARGET_MEMORY="${TARGET_MEMORY:-$DEFAULT_MEMORY}"

TARGET_MONITOR="${AGENTD_MONITOR_SERVICE_URL:+$(extract_host_port "$AGENTD_MONITOR_SERVICE_URL")}"
TARGET_MONITOR="${TARGET_MONITOR:-$DEFAULT_MONITOR}"

# --- Generate prometheus.yml -----------------------------------------
cat > "$OUTPUT" << EOF
# Prometheus configuration for agentd local observability stack.
#
# Auto-generated by generate-config.sh (AGENTD_ENV=${ENV}).
# Re-run ./infra/update.sh to regenerate and install.
#
# Usage:
#   prometheus --config.file=<this file>

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: '${ENV_LABEL}'
    cluster: 'agentd-local'

scrape_configs:
  # Orchestrator - agent management, workflow scheduling, dispatch
  - job_name: 'agentd-orchestrator'
    static_configs:
      - targets: ['${TARGET_ORCHESTRATOR}']
        labels:
          service: 'orchestrator'

  # Communicate - WebSocket rooms and real-time messaging
  - job_name: 'agentd-communicate'
    static_configs:
      - targets: ['${TARGET_COMMUNICATE}']
        labels:
          service: 'communicate'

  # Notify - notification ingestion and delivery
  - job_name: 'agentd-notify'
    static_configs:
      - targets: ['${TARGET_NOTIFY}']
        labels:
          service: 'notify'

  # Ask - approval requests and human-in-the-loop gates
  - job_name: 'agentd-ask'
    static_configs:
      - targets: ['${TARGET_ASK}']
        labels:
          service: 'ask'

  # Wrap - PTY session and tmux agent launcher
  - job_name: 'agentd-wrap'
    static_configs:
      - targets: ['${TARGET_WRAP}']
        labels:
          service: 'wrap'

  # Memory - vector-backed knowledge store
  - job_name: 'agentd-memory'
    static_configs:
      - targets: ['${TARGET_MEMORY}']
        labels:
          service: 'memory'

  # Monitor - system monitoring and health checks
  # Uses /prom-metrics to avoid conflict with the JSON /metrics endpoint
  - job_name: 'agentd-monitor'
    metrics_path: '/prom-metrics'
    static_configs:
      - targets: ['${TARGET_MONITOR}']
        labels:
          service: 'monitor'
EOF

if [ "$OUTPUT" != "/dev/stdout" ]; then
  echo "Generated ${OUTPUT} (env=${ENV})" >&2
fi
