//! Core notification types and data structures.
//!
//! This module defines the fundamental types used throughout the notification system,
//! including sources, lifetimes, priorities, statuses, and the main [`Notification`] struct.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// The origin of a notification.
///
/// Notifications can come from various sources within the agentd system.
/// Each source provides context about where the notification was generated.
///
/// # Examples
///
/// ```
/// use notify::types::NotificationSource;
/// use uuid::Uuid;
///
/// // System notification
/// let source = NotificationSource::System;
///
/// // From the ask service
/// let source = NotificationSource::AskService {
///     request_id: Uuid::new_v4(),
/// };
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum NotificationSource {
    /// From an agent hook requiring user input.
    ///
    /// These notifications are generated when an agent encounters a situation
    /// that requires user interaction or approval.
    AgentHook {
        /// Unique identifier for the agent that generated this notification
        agent_id: String,
        /// Type of hook that triggered the notification
        hook_type: String,
    },

    /// From the agentd-ask service.
    ///
    /// These notifications ask the user questions about their environment
    /// or preferences (e.g., "Do you want to start a tmux session?").
    AskService {
        /// Unique identifier for this ask request
        request_id: Uuid,
    },

    /// From the agentd-monitor service.
    ///
    /// These notifications are generated by the monitoring system when
    /// it detects conditions worth alerting about.
    MonitorService {
        /// Type of alert being sent (e.g., "high_cpu", "disk_space")
        alert_type: String,
    },

    /// System-generated notification.
    ///
    /// Generic notifications from the system itself, not tied to a specific service.
    System,
}

/// Lifetime behavior of a notification
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum NotificationLifetime {
    /// Ephemeral notifications expire after a timeout
    /// These are typically tied to active processes and can't be acted on after expiration
    Ephemeral { expires_at: DateTime<Utc> },
    /// Persistent notifications remain until explicitly dismissed
    /// These typically represent requests that can be responded to at any time
    Persistent,
}

impl NotificationLifetime {
    /// Check if this notification has expired.
    ///
    /// Returns `true` if this is an ephemeral notification whose expiration
    /// time has passed, or `false` otherwise. Persistent notifications never expire.
    ///
    /// # Examples
    ///
    /// ```
    /// use notify::types::NotificationLifetime;
    /// use chrono::Duration;
    ///
    /// // Already expired
    /// let lifetime = NotificationLifetime::ephemeral(Duration::milliseconds(-1));
    /// assert!(lifetime.is_expired());
    ///
    /// // Never expires
    /// let lifetime = NotificationLifetime::Persistent;
    /// assert!(!lifetime.is_expired());
    /// ```
    pub fn is_expired(&self) -> bool {
        match self {
            NotificationLifetime::Ephemeral { expires_at } => Utc::now() > *expires_at,
            NotificationLifetime::Persistent => false,
        }
    }

    /// Create an ephemeral notification that expires after the given duration.
    ///
    /// # Arguments
    ///
    /// * `duration` - How long from now until the notification expires
    ///
    /// # Examples
    ///
    /// ```
    /// use notify::types::NotificationLifetime;
    /// use chrono::Duration;
    ///
    /// // Expires in 30 seconds
    /// let lifetime = NotificationLifetime::ephemeral(Duration::seconds(30));
    ///
    /// // Expires in 1 hour
    /// let lifetime = NotificationLifetime::ephemeral(Duration::hours(1));
    /// ```
    #[allow(dead_code)]
    pub fn ephemeral(duration: chrono::Duration) -> Self {
        NotificationLifetime::Ephemeral { expires_at: Utc::now() + duration }
    }
}

/// Priority level for notifications.
///
/// Priorities help users focus on the most important notifications first.
/// They are ordered from lowest to highest: Low < Normal < High < Urgent.
///
/// # Priority Guidelines
///
/// - **Low**: Informational, no action required (e.g., "Build completed successfully")
/// - **Normal**: Standard notifications requiring attention (e.g., "Code review assigned")
/// - **High**: Important notifications requiring prompt attention (e.g., "Test failure")
/// - **Urgent**: Critical notifications requiring immediate action (e.g., "Production system down")
///
/// # Examples
///
/// ```
/// use notify::types::NotificationPriority;
///
/// let low = NotificationPriority::Low;
/// let urgent = NotificationPriority::Urgent;
///
/// assert!(urgent > low); // Priorities are comparable
/// ```
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum NotificationPriority {
    /// Low priority - informational only
    Low,
    /// Normal priority - standard notification
    Normal,
    /// High priority - important, needs attention soon
    High,
    /// Urgent priority - critical, needs immediate attention
    Urgent,
}

impl std::str::FromStr for NotificationPriority {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "low" => Ok(NotificationPriority::Low),
            "normal" => Ok(NotificationPriority::Normal),
            "high" => Ok(NotificationPriority::High),
            "urgent" => Ok(NotificationPriority::Urgent),
            _ => anyhow::bail!("Invalid priority: {s}"),
        }
    }
}

/// Current status of a notification in its lifecycle.
///
/// Notifications progress through various states as they are created,
/// viewed, acted upon, or expire.
///
/// # Status Transitions
///
/// ```text
/// Pending → Viewed → Responded
///    ↓         ↓
/// Dismissed  Dismissed
///    ↓
/// Expired (ephemeral only)
/// ```
///
/// # Examples
///
/// ```
/// use notify::types::NotificationStatus;
///
/// let status = NotificationStatus::Pending;
/// assert_eq!(status, NotificationStatus::Pending);
/// ```
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum NotificationStatus {
    /// Notification is pending user action.
    ///
    /// This is the initial state of all newly created notifications.
    Pending,

    /// User has viewed the notification.
    ///
    /// The notification has been seen but not yet acted upon.
    Viewed,

    /// User has responded to the notification.
    ///
    /// Only applicable to notifications that require a response.
    Responded,

    /// Notification has been dismissed.
    ///
    /// The user has explicitly dismissed this notification.
    Dismissed,

    /// Notification has expired (only for ephemeral notifications).
    ///
    /// The notification's expiration time has passed and it is no longer actionable.
    Expired,
}

impl std::str::FromStr for NotificationStatus {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "pending" => Ok(NotificationStatus::Pending),
            "viewed" => Ok(NotificationStatus::Viewed),
            "responded" => Ok(NotificationStatus::Responded),
            "dismissed" => Ok(NotificationStatus::Dismissed),
            "expired" => Ok(NotificationStatus::Expired),
            _ => anyhow::bail!("Invalid status: {s}"),
        }
    }
}

/// A complete notification in the system.
///
/// Notifications are the core data structure, containing all information about
/// an alert, message, or request that needs user attention.
///
/// # Lifecycle
///
/// 1. Created with [`Notification::new`]
/// 2. Stored via [`crate::storage::NotificationStorage::add`]
/// 3. Retrieved and updated via the storage API
/// 4. Eventually dismissed, responded to, or expired
///
/// # Examples
///
/// ```
/// use notify::types::*;
///
/// let notification = Notification::new(
///     NotificationSource::System,
///     NotificationLifetime::Persistent,
///     NotificationPriority::Normal,
///     "Welcome".to_string(),
///     "System is ready".to_string(),
///     false,
/// );
///
/// assert!(notification.is_actionable());
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Notification {
    /// Unique identifier for this notification.
    ///
    /// Generated automatically using UUID v4 when the notification is created.
    pub id: Uuid,

    /// Source of the notification.
    ///
    /// Indicates which service or component generated this notification.
    pub source: NotificationSource,

    /// Lifetime behavior.
    ///
    /// Determines whether this notification expires or remains indefinitely.
    pub lifetime: NotificationLifetime,

    /// Priority level.
    ///
    /// Higher priority notifications should be shown more prominently.
    pub priority: NotificationPriority,

    /// Current status.
    ///
    /// Tracks the notification's state through its lifecycle.
    pub status: NotificationStatus,

    /// Title of the notification.
    ///
    /// A short, descriptive summary (typically one line).
    pub title: String,

    /// Message body.
    ///
    /// The detailed content of the notification. Can be multiple lines.
    pub message: String,

    /// Whether this notification requires a response.
    ///
    /// If `true`, the user should provide a text response via [`Notification::set_response`].
    pub requires_response: bool,

    /// User's response (if any).
    ///
    /// Contains the user's response text if they've responded to this notification.
    pub response: Option<String>,

    /// When the notification was created.
    ///
    /// Timestamp in UTC when this notification was first created.
    pub created_at: DateTime<Utc>,

    /// When the notification was last updated.
    ///
    /// Timestamp in UTC of the last modification to this notification.
    pub updated_at: DateTime<Utc>,
}

impl Notification {
    /// Create a new notification with the given parameters.
    ///
    /// This is the primary constructor for creating notifications. It automatically
    /// generates a UUID, sets the status to `Pending`, and initializes timestamps.
    ///
    /// # Arguments
    ///
    /// * `source` - Where the notification originated from
    /// * `lifetime` - How long the notification should remain active
    /// * `priority` - Importance level of the notification
    /// * `title` - Short, descriptive title
    /// * `message` - Detailed message content
    /// * `requires_response` - Whether the user must provide a text response
    ///
    /// # Examples
    ///
    /// ```
    /// use notify::types::*;
    ///
    /// // Create a high-priority system notification
    /// let notification = Notification::new(
    ///     NotificationSource::System,
    ///     NotificationLifetime::Persistent,
    ///     NotificationPriority::High,
    ///     "Action Required".to_string(),
    ///     "Please review the latest changes".to_string(),
    ///     false,
    /// );
    /// ```
    pub fn new(
        source: NotificationSource,
        lifetime: NotificationLifetime,
        priority: NotificationPriority,
        title: String,
        message: String,
        requires_response: bool,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            source,
            lifetime,
            priority,
            status: NotificationStatus::Pending,
            title,
            message,
            requires_response,
            response: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Check if this notification is still actionable
    /// Check if this notification can still be acted upon.
    ///
    /// Returns `true` if the notification is in Pending or Viewed status and has not expired.
    /// This is useful for filtering out notifications that no longer need attention.
    ///
    /// # Examples
    ///
    /// ```
    /// use notify::types::*;
    ///
    /// let notif = Notification::new(
    ///     NotificationSource::System,
    ///     NotificationLifetime::Persistent,
    ///     NotificationPriority::Normal,
    ///     "Test".to_string(),
    ///     "Message".to_string(),
    ///     false,
    /// );
    ///
    /// assert!(notif.is_actionable());
    /// ```
    pub fn is_actionable(&self) -> bool {
        matches!(self.status, NotificationStatus::Pending | NotificationStatus::Viewed)
            && !self.lifetime.is_expired()
    }

    /// Mark the notification as viewed
    #[allow(dead_code)]
    /// Mark this notification as viewed by the user.
    ///
    /// Transitions the notification from Pending to Viewed status if it was pending.
    /// Updates the `updated_at` timestamp.
    ///
    /// This method has no effect if the notification is already in a different status.
    pub fn mark_viewed(&mut self) {
        if self.status == NotificationStatus::Pending {
            self.status = NotificationStatus::Viewed;
            self.updated_at = Utc::now();
        }
    }

    /// Set the response for this notification
    /// Set the user's response to this notification.
    ///
    /// This method can only be called on notifications that require a response
    /// and are still actionable. It transitions the notification to Responded status.
    ///
    /// # Arguments
    ///
    /// * `response` - The user's text response
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The notification does not require a response
    /// - The notification is no longer actionable (expired or dismissed)
    ///
    /// # Examples
    ///
    /// ```
    /// use notify::types::*;
    ///
    /// let mut notif = Notification::new(
    ///     NotificationSource::System,
    ///     NotificationLifetime::Persistent,
    ///     NotificationPriority::Normal,
    ///     "Question".to_string(),
    ///     "Do you approve?".to_string(),
    ///     true, // requires response
    /// );
    ///
    /// notif.set_response("Yes, approved".to_string()).unwrap();
    /// assert_eq!(notif.response, Some("Yes, approved".to_string()));
    /// ```
    pub fn set_response(&mut self, response: String) -> anyhow::Result<()> {
        if !self.requires_response {
            anyhow::bail!("This notification does not accept responses");
        }
        if !self.is_actionable() {
            anyhow::bail!("This notification is no longer actionable");
        }

        self.response = Some(response);
        self.status = NotificationStatus::Responded;
        self.updated_at = Utc::now();
        Ok(())
    }

    /// Dismiss the notification
    #[allow(dead_code)]
    /// Dismiss this notification.
    ///
    /// Marks the notification as dismissed and updates the timestamp.
    /// Dismissed notifications are removed from actionable lists.
    pub fn dismiss(&mut self) {
        self.status = NotificationStatus::Dismissed;
        self.updated_at = Utc::now();
    }

    /// Update status based on lifetime expiration
    #[allow(dead_code)]
    /// Update the notification status if it has expired.
    ///
    /// Checks if an ephemeral notification has expired and updates its status
    /// to Expired if it was still Pending. This method should be called
    /// periodically to clean up expired notifications.
    pub fn update_expiration_status(&mut self) {
        if self.lifetime.is_expired() && self.status == NotificationStatus::Pending {
            self.status = NotificationStatus::Expired;
            self.updated_at = Utc::now();
        }
    }
}

/// Request to create a new notification.
///
/// Contains all information needed to create a notification in the notification service.
///
/// # JSON Example
///
/// ```json
/// {
///   "source": {"type": "system"},
///   "lifetime": {"type": "persistent"},
///   "priority": "normal",
///   "title": "Question",
///   "message": "Do you want to continue?",
///   "requires_response": true
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateNotificationRequest {
    /// Source identifier for the notification
    pub source: NotificationSource,
    /// Lifetime behavior (ephemeral or persistent)
    pub lifetime: NotificationLifetime,
    /// Priority level
    pub priority: NotificationPriority,
    /// Notification title
    pub title: String,
    /// Notification message body
    pub message: String,
    /// Whether this notification requires a response
    pub requires_response: bool,
}

/// Request to update an existing notification.
///
/// Only includes fields that should be updated. Fields set to `None` are not
/// included in the JSON (via `skip_serializing_if`).
///
/// # JSON Example
///
/// ```json
/// {
///   "status": "responded",
///   "response": "yes"
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateNotificationRequest {
    /// Updated status (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<NotificationStatus>,
    /// User's response text (optional)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub response: Option<String>,
}

/// Count of notifications for a specific status.
///
/// Used in the count endpoint response to show how many notifications
/// exist in each status category.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StatusCount {
    /// The status name (e.g., "pending", "viewed", "responded")
    pub status: String,
    /// Number of notifications with this status
    pub count: usize,
}

/// Response from the count endpoint.
///
/// Contains the total notification count and a breakdown by status.
///
/// # JSON Example
///
/// ```json
/// {
///   "total": 42,
///   "by_status": [
///     {"status": "pending", "count": 15},
///     {"status": "viewed", "count": 10}
///   ]
/// }
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CountResponse {
    /// Total number of notifications across all statuses
    pub total: usize,
    /// Count breakdown by status
    pub by_status: Vec<StatusCount>,
}

/// Paginated response envelope for list endpoints.
///
/// Wraps a list of items with pagination metadata.
///
/// # JSON Example
///
/// ```json
/// {
///   "items": [...],
///   "total": 150,
///   "limit": 20,
///   "offset": 0
/// }
/// ```
// Re-export pagination types from agentd-common.
pub use agentd_common::types::{clamp_limit, PaginatedResponse, DEFAULT_PAGE_LIMIT, MAX_PAGE_LIMIT};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ephemeral_notification_expiry() {
        let lifetime = NotificationLifetime::ephemeral(chrono::Duration::milliseconds(-1));
        assert!(lifetime.is_expired());
    }

    #[test]
    fn test_persistent_notification_never_expires() {
        let lifetime = NotificationLifetime::Persistent;
        assert!(!lifetime.is_expired());
    }

    #[test]
    fn test_notification_creation() {
        let notification = Notification::new(
            NotificationSource::System,
            NotificationLifetime::Persistent,
            NotificationPriority::Normal,
            "Test".to_string(),
            "Test message".to_string(),
            false,
        );

        assert_eq!(notification.status, NotificationStatus::Pending);
        assert!(notification.is_actionable());
    }

    #[test]
    fn test_notification_response() {
        let mut notification = Notification::new(
            NotificationSource::System,
            NotificationLifetime::Persistent,
            NotificationPriority::Normal,
            "Test".to_string(),
            "Test message".to_string(),
            true,
        );

        let result = notification.set_response("My response".to_string());
        assert!(result.is_ok());
        assert_eq!(notification.response, Some("My response".to_string()));
        assert_eq!(notification.status, NotificationStatus::Responded);
    }

    #[test]
    fn test_notification_no_response_when_not_required() {
        let mut notification = Notification::new(
            NotificationSource::System,
            NotificationLifetime::Persistent,
            NotificationPriority::Normal,
            "Test".to_string(),
            "Test message".to_string(),
            false,
        );

        let result = notification.set_response("My response".to_string());
        assert!(result.is_err());
    }

    #[test]
    fn test_expired_notification_not_actionable() {
        let mut notification = Notification::new(
            NotificationSource::System,
            NotificationLifetime::ephemeral(chrono::Duration::milliseconds(-1)),
            NotificationPriority::Normal,
            "Test".to_string(),
            "Test message".to_string(),
            true,
        );

        notification.update_expiration_status();
        assert!(!notification.is_actionable());
        assert_eq!(notification.status, NotificationStatus::Expired);
    }
}
